import dotenv from 'dotenv';

dotenv.config();

export interface AppConfig {
  PORT: number;
  HOST: string;
  DEFAULT_TOPIC_PICK_TIME_SECONDS: number;
  DEFAULT_ANSWER_TIME_SECONDS: number;
  DEFAULT_BLUFF_TIME_SECONDS: number;
  DEFAULT_VOTE_TIME_SECONDS: number;
  DEFAULT_REVEAL_TIME_SECONDS: number;
  MIN_PLAYERS_TO_START: number;
  MAX_PLAYERS_PER_ROOM: number;
  DEFAULT_TOTAL_ROUNDS: number;
  ROOM_CLEANUP_INTERVAL_MS: number;
  ROOM_MAX_IDLE_TIME_MS: number;
  RECONNECT_GRACE_PERIOD_MS: number;
}

export const config: AppConfig = {
  PORT: process.env.PORT ? parseInt(process.env.PORT, 10) : 3000,
  HOST: process.env.HOST || '0.0.0.0',
  DEFAULT_TOPIC_PICK_TIME_SECONDS: 30,
  DEFAULT_ANSWER_TIME_SECONDS: 60,
  DEFAULT_BLUFF_TIME_SECONDS: 45,
  DEFAULT_VOTE_TIME_SECONDS: 40,
  DEFAULT_REVEAL_TIME_SECONDS: 20,
  MIN_PLAYERS_TO_START: 2,
  MAX_PLAYERS_PER_ROOM: 12,
  DEFAULT_TOTAL_ROUNDS: 5,
  ROOM_CLEANUP_INTERVAL_MS: 5 * 60 * 1000, // 5 minutes
  ROOM_MAX_IDLE_TIME_MS: 30 * 60 * 1000, // 30 minutes
  RECONNECT_GRACE_PERIOD_MS: 60 * 1000, // 60 seconds
};
